<!DOCTYPE html>
<html>
<body>
<div class = "table-content">
<?php
$servername = "localhost";
$username = "root";
$password = "";
$dbname = "yahoodata";

// Create connection
$conn = new mysqli($servername, $username, $password, $dbname);
// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

//$List = ["SBIN.NS","PNB.NS","DABUR.NS","BOSCHLTD.NS","APOLLOTYRE.NS","ONGC.NS","NTPC.NS","POWERGRID.NS","ICICIPRULI.NS","PFC.NS","BAJAJHLDNG.NS","IBULHSGFIN.NS","MARUTI.NS","EXIDEIND.NS","HEROMOTOCO.NS","BAJAJ-AUTO.NS","EICHERMOT.NS","TVSMOTOR.NS","BHARATFORG.NS","KOTAKBANK.NS","ADANIPOWER.NS","ZEEL.NS","TATASTEEL.NS","YESBANK.NS","WIPRO.NS","UPL.NS","UNIONBANK.NS","VEDL.NS","HINDALCO.NS","TATAMOTORS.NS","TATAPOWER.NS","SAIL.NS","RBLBANK.NS","BANDHANBNK.NS","MOTHERSUMI.NS","NCC.NS","NBCC.NS","JSWSTEEL.NS","LT.NS","JINDALSTEL.NS","IDFC.NS","ITC.NS","INFRATEL.NS","IOC.NS","GLENMARK.NS","COALINDIA.NS","GMRINFRA.NS","HDFCBANK.NS","EDELWEISS.NS","ICICIGI.NS","GAIL.NS","FEDERALBNK.NS","BPCL.NS","ABCAPITAL.NS","ASHOKLEY.NS","AXISBANK.NS","IDFCFIRSTB.NS","INDUSINDBK.NS","ICICIBANK.NS","BANKINDIA.NS","BANKBARODA.NS","BEL.NS","BERGEPAINT.NS","BHEL.NS","BHARTIARTL.NS","BIOCON.NS","EQUITAS.NS","FCONSUMER.NS","INFIBEAM.NS","M&M.NS","INFY.NS","PEL.NS","AUROPHARMA.NS","DRREDDY.NS","DIVISLAB.NS","CIPLA.NS","LUPIN.NS","SUNP//HARMA.NS","CADILAHC.NS","BAJAJFINSV.NS","M&MFIN.NS","BRITANNIA.NS","COLPAL.NS","GODREJCP.NS","TATACONSUM.NS","MARICO.NS","JUBLFOOD.NS","EMAMILTD.NS","GODREJIND.NS","UBL.NS","MCDOWELL-N.NS","TATAELXSI.NS","MINDTREE.NS","HEXAWARE.NS","HCLTECH.NS","TECHM.NS","NIITTECH.NS","TCS.NS","JUSTDIAL.NS","SAREGAMA.NS","INOXLEISUR.NS","PVR.NS","SUNTV.NS","HINDZINC.NS","HINDCOPPER.NS","RATNAMANI.NS","PRESTIGE.NS","OBEROIRLTY.NS","GODREJPROP.NS","SUNTECK.NS"];



$List = ['3MINDIA.NS', 'AARTIIND.NS', 'AAVAS.NS', 'ABBOTINDIA.NS', 'ABCAPITAL.NS', 'ABFRL.NS', 'ACC.NS', 'ADANIGAS.NS', 'ADANIGREEN.NS', 'ADANIPORTS.NS', 'ADANIPOWER.NS', 'ADANITRANS.NS', 'ADVENZYMES.NS', 'AEGISCHEM.NS', 'AFFLE.NS', 'AIAENG.NS', 'AJANTPHARM.NS', 'AKZOINDIA.NS', 'ALKEM.NS', 'ALLCARGO.NS', 'AMARAJABAT.NS', 'AMBER.NS', 'AMBUJACEM.NS', 'APLAPOLLO.NS', 'APLLTD.NS', 'APOLLOHOSP.NS', 'APOLLOTYRE.NS', 'ARVINDFASN.NS', 'ASAHIINDIA.NS', 'ASHOKA.NS', 'ASHOKLEY.NS', 'ASIANPAINT.NS', 'ASTERDM.NS', 'ASTRAL.NS', 'ASTRAZEN.NS', 'ATUL.NS', 'AUBANK.NS', 'AUROPHARMA.NS', 'AVANTIFEED.NS', 'AXISBANK.NS', 'BAJAJ-AUTO.NS', 'BAJAJCON.NS', 'BAJAJELEC.NS', 'BAJAJFINSV.NS', 'BAJAJHLDNG.NS', 'BAJFINANCE.NS', 'BALKRISIND.NS', 'BALMLAWRIE.NS', 'BALRAMCHIN.NS', 'BANDHANBNK.NS', 'BANKBARODA.NS', 'BANKINDIA.NS', 'BASF.NS', 'BATAINDIA.NS', 'BAYERCROP.NS', 'BBTC.NS', 'BDL.NS', 'BEL.NS', 'BEML.NS', 'BERGEPAINT.NS', 'BHARATFORG.NS', 'BHARTIARTL.NS', 'BHEL.NS', 'BIOCON.NS', 'BIRLACORPN.NS', 'BLISSGVS.NS', 'BLUEDART.NS', 'BLUESTARCO.NS', 'BOMDYEING.NS', 'BOSCHLTD.NS', 'BPCL.NS', 'BRIGADE.NS', 'BRITANNIA.NS', 'BSE.NS', 'BSOFT.NS', 'CADILAHC.NS', 'CANBK.NS', 'CANFINHOME.NS', 'CAPLIPOINT.NS', 'CARBORUNIV.NS', 'CARERATING.NS', 'CASTROLIND.NS', 'CCL.NS', 'CDSL.NS', 'CEATLTD.NS', 'CENTRALBK.NS', 'CENTURYPLY.NS', 'CERA.NS', 'CESC.NS', 'CGCL.NS', 'CHALET.NS', 'CHAMBLFERT.NS', 'CHENNPETRO.NS', 'CHOLAFIN.NS', 'CHOLAHLDNG.NS', 'CIPLA.NS', 'COALINDIA.NS', 'COCHINSHIP.NS', 'COLPAL.NS', 'CONCOR.NS', 'COROMANDEL.NS', 'CREDITACC.NS', 'CRISIL.NS', 'CROMPTON.NS', 'CUB.NS', 'CUMMINSIND.NS', 'CYIENT.NS', 'DABUR.NS', 'DALBHARAT.NS', 'DBCORP.NS', 'DBL.NS', 'DCAL.NS', 'DCBBANK.NS', 'DCMSHRIRAM.NS', 'DEEPAKNTR.NS', 'DELTACORP.NS', 'DHFL.NS', 'DISHTV.NS', 'DIVISLAB.NS', 'DIXON.NS', 'DLF.NS', 'DMART.NS', 'DRREDDY.NS', 'ECLERX.NS', 'EDELWEISS.NS', 'EICHERMOT.NS', 'EIDPARRY.NS', 'EIHOTEL.NS', 'ELGIEQUIP.NS', 'EMAMILTD.NS', 'ENDURANCE.NS', 'ENGINERSIN.NS', 'EQUITAS.NS', 'ERIS.NS', 'ESCORTS.NS', 'ESSELPACK.NS', 'EXIDEIND.NS', 'FCONSUMER.NS', 'FDC.NS', 'FEDERALBNK.NS', 'FINCABLES.NS', 'FINEORG.NS', 'FINPIPE.NS', 'FLFL.NS', 'FMGOETZE.NS', 'FORTIS.NS', 'FRETAIL.NS', 'FSL.NS', 'GAIL.NS', 'GALAXYSURF.NS', 'GARFIBRES.NS', 'GAYAPROJ.NS', 'GEPIL.NS', 'GESHIP.NS', 'GET&D.NS', 'GHCL.NS', 'GICRE.NS', 'GILLETTE.NS', 'GLAXO.NS', 'GLENMARK.NS', 'GMDCLTD.NS', 'GMRINFRA.NS', 'GNFC.NS', 'GODFRYPHLP.NS', 'GODREJAGRO.NS', 'GODREJCP.NS', 'GODREJIND.NS', 'GODREJPROP.NS', 'GPPL.NS', 'GRANULES.NS', 'GRAPHITE.NS', 'GRASIM.NS', 'GREAVESCOT.NS', 'GRINDWELL.NS', 'GSFC.NS', 'GSPL.NS', 'GUJALKALI.NS', 'GUJGASLTD.NS', 'GULFOILLUB.NS', 'HAL.NS', 'HATSUN.NS', 'HAVELLS.NS', 'HCLTECH.NS', 'HDFC.NS', 'HDFCAMC.NS', 'HDFCBANK.NS', 'HDFCLIFE.NS', 'HEG.NS', 'HEIDELBERG.NS', 'HERITGFOOD.NS', 'HEROMOTOCO.NS', 'HEXAWARE.NS', 'HFCL.NS', 'HIMATSEIDE.NS', 'HINDALCO.NS', 'HINDCOPPER.NS', 'HINDPETRO.NS', 'HINDUNILVR.NS', 'HINDZINC.NS', 'HONAUT.NS', 'HSCL.NS', 'HUDCO.NS', 'IBREALEST.NS', 'IBULHSGFIN.NS', 'IBULISL.NS', 'IBVENTURES.NS', 'ICICIBANK.NS', 'ICICIGI.NS', 'ICICIPRULI.NS', 'ICRA.NS', 'IDBI.NS', 'IDEA.NS', 'IDFC.NS', 'IDFCFIRSTB.NS', 'IEX.NS', 'IFBIND.NS', 'IFCI.NS', 'IGL.NS', 'IIFL.NS', 'INDHOTEL.NS', 'INDIACEM.NS', 'INDIAMART.NS', 'INDIANB.NS', 'INDIGO.NS', 'INDOSTAR.NS', 'INDUSINDBK.NS', 'INFIBEAM.NS', 'INFRATEL.NS', 'INFY.NS', 'INOXLEISUR.NS', 'INTELLECT.NS', 'IOB.NS', 'IOC.NS', 'IPCALAB.NS', 'IRB.NS', 'IRCON.NS', 'ISEC.NS', 'ITC.NS', 'ITDC.NS', 'ITDCEM.NS', 'ITI.NS', 'J&KBANK.NS', 'JAGRAN.NS', 'JAICORPLTD.NS', 'JAMNAAUTO.NS', 'JBCHEPHARM.NS', 'JCHAC.NS', 'JINDALSAW.NS', 'JINDALSTEL.NS', 'JISLJALEQS.NS', 'JKCEMENT.NS', 'JKLAKSHMI.NS', 'JKPAPER.NS', 'JKTYRE.NS', 'JMFINANCIL.NS', 'JSL.NS', 'JSLHISAR.NS', 'JSWENERGY.NS', 'JSWSTEEL.NS', 'JUBILANT.NS', 'JUBLFOOD.NS', 'JUSTDIAL.NS', 'JYOTHYLAB.NS', 'KAJARIACER.NS', 'KALPATPOWR.NS', 'KANSAINER.NS', 'KARURVYSYA.NS', 'KEC.NS', 'KEI.NS', 'KENNAMET.NS', 'KIRLOSENG.NS', 'KNRCON.NS', 'KOLTEPATIL.NS', 'KOTAKBANK.NS', 'KPITTECH.NS', 'KPRMILL.NS', 'KRBL.NS', 'KSCL.NS', 'KTKBANK.NS', 'L&TFH.NS', 'LAKSHVILAS.NS', 'LALPATHLAB.NS', 'LAURUSLABS.NS', 'LAXMIMACH.NS', 'LEMONTREE.NS', 'LICHSGFIN.NS', 'LINDEINDIA.NS', 'LT.NS', 'LTI.NS', 'LTTS.NS', 'LUPIN.NS', 'LUXIND.NS', 'M&M.NS', 'M&MFIN.NS', 'MAGMA.NS', 'MAHABANK.NS', 'MAHINDCIE.NS', 'MAHLOG.NS', 'MAHSCOOTER.NS', 'MAHSEAMLES.NS', 'MANAPPURAM.NS', 'MARICO.NS', 'MARUTI.NS', 'MASFIN.NS', 'MCDOWELL-N.NS', 'MCX.NS', 'METROPOLIS.NS', 'MFSL.NS', 'MGL.NS', 'MHRIL.NS', 'MIDHANI.NS', 'MINDACORP.NS', 'MINDAIND.NS', 'MINDTREE.NS', 'MMTC.NS', 'MOIL.NS', 'MOTHERSUMI.NS', 'MOTILALOFS.NS', 'MPHASIS.NS', 'MRF.NS', 'MRPL.NS', 'MUTHOOTFIN.NS', 'NAM-INDIA.NS', 'NATCOPHARM.NS', 'NATIONALUM.NS', 'NAUKRI.NS', 'NAVINFLUOR.NS', 'NBCC.NS', 'NBVENTURES.NS', 'NCC.NS', 'NESCO.NS', 'NESTLEIND.NS', 'NETWORK18.NS', 'NFL.NS', 'NH.NS', 'NHPC.NS', 'NIACL.NS', 'NIITTECH.NS', 'NILKAMAL.NS', 'NLCINDIA.NS', 'NMDC.NS', 'NTPC.NS', 'OBEROIRLTY.NS', 'OFSS.NS', 'OIL.NS', 'OMAXE.NS', 'ONGC.NS', 'ORIENTCEM.NS', 'ORIENTELEC.NS', 'ORIENTREF.NS', 'PAGEIND.NS', 'PARAGMILK.NS', 'PCJEWELLER.NS', 'PEL.NS', 'PERSISTENT.NS', 'PETRONET.NS', 'PFC.NS', 'PFIZER.NS', 'PGHH.NS', 'PGHL.NS', 'PHILIPCARB.NS', 'PHOENIXLTD.NS', 'PIDILITIND.NS', 'PIIND.NS', 'PNB.NS', 'PNBHOUSING.NS', 'PNCINFRA.NS', 'POLYCAB.NS', 'POWERGRID.NS', 'PRAJIND.NS', 'PRESTIGE.NS', 'PRSMJOHNSN.NS', 'PTC.NS', 'PVR.NS', 'QUESS.NS', 'RADICO.NS', 'RAIN.NS', 'RAJESHEXPO.NS', 'RALLIS.NS', 'RAMCOCEM.NS', 'RATNAMANI.NS', 'RAYMOND.NS', 'RBLBANK.NS', 'RCF.NS', 'RECLTD.NS', 'REDINGTON.NS', 'RELAXO.NS', 'RELCAPITAL.NS', 'RELIANCE.NS', 'RELINFRA.NS', 'RENUKA.NS', 'REPCOHOME.NS', 'RESPONIND.NS', 'RITES.NS', 'RPOWER.NS', 'RVNL.NS', 'SADBHAV.NS', 'SAIL.NS', 'SANOFI.NS', 'SAREGAMA.NS', 'SBILIFE.NS', 'SBIN.NS', 'SCHAEFFLER.NS', 'SFL.NS', 'SHILPAMED.NS', 'SHK.NS', 'SHOPERSTOP.NS', 'SHREECEM.NS', 'SHRIRAMCIT.NS', 'SIEMENS.NS', 'SIS.NS', 'SJVN.NS', 'SKFINDIA.NS', 'SOBHA.NS', 'SOLARINDS.NS', 'SONATSOFTW.NS', 'SOUTHBANK.NS', 'SPANDANA.NS', 'SPARC.NS', 'SPICEJET.NS', 'SRF.NS', 'SRTRANSFIN.NS', 'STAR.NS', 'STARCEMENT.NS', 'STRTECH.NS', 'SUDARSCHEM.NS', 'SUNCLAYLTD.NS', 'SUNDARMFIN.NS', 'SUNDRMFAST.NS', 'SUNPHARMA.NS', 'SUNTECK.NS', 'SUNTV.NS', 'SUPRAJIT.NS', 'SUPREMEIND.NS', 'SUZLON.NS', 'SWANENERGY.NS', 'SWSOLAR.NS', 'SYMPHONY.NS', 'SYNGENE.NS', 'TAKE.NS', 'TASTYBITE.NS', 'TATACONSUM.NS', 'TATAELXSI.NS', 'TATAINVEST.NS', 'TATAMOTORS.NS', 'TATAMTRDVR.NS', 'TATAPOWER.NS', 'TATASTEEL.NS', 'TATASTLBSL.NS', 'TCIEXP.NS', 'TCNSBRANDS.NS', 'TCS.NS', 'TEAMLEASE.NS', 'TECHM.NS', 'TECHNOE.NS', 'THERMAX.NS', 'THYROCARE.NS', 'TIINDIA.NS', 'TIMETECHNO.NS', 'TIMKEN.NS', 'TITAN.NS', 'TORNTPHARM.NS', 'TORNTPOWER.NS', 'TRENT.NS', 'TRIDENT.NS', 'TRITURBINE.NS', 'TTKPRESTIG.NS', 'TV18BRDCST.NS', 'TVSMOTOR.NS', 'TVTODAY.NS', 'UBL.NS', 'UCOBANK.NS', 'UFLEX.NS', 'UJJIVAN.NS', 'ULTRACEMCO.NS', 'UNIONBANK.NS', 'UPL.NS', 'VAIBHAVGBL.NS', 'VAKRANGEE.NS', 'VARROC.NS', 'VBL.NS', 'VEDL.NS', 'VENKEYS.NS', 'VGUARD.NS', 'VINATIORGA.NS', 'VIPIND.NS', 'VMART.NS', 'VOLTAS.NS', 'VRLLOG.NS', 'VSTIND.NS', 'VTL.NS', 'WABAG.NS', 'WABCOINDIA.NS', 'WELCORP.NS', 'WELSPUNIND.NS', 'WESTLIFE.NS', 'WHIRLPOOL.NS', 'WIPRO.NS', 'WOCKPHARMA.NS', 'YESBANK.NS', 'ZEEL.NS', 'ZENSARTECH.NS', 'ZYDUSWELL.NS'];
 
echo '<table class= "table table-sm table-bordered table-hover"><thead class = "thead-dark"><tr><th>Ticker</th><th>Ema Crossover</th><th>Adx Value</th><th>RSI Value</th></tr></thead>';

foreach($List as $value){
$append = "_swingtrading_technical_value";
$sql = "SELECT *  FROM `".$value.$append."` ORDER BY rsivalue DESC LIMIT 1";

$result = $conn->query($sql);

if ($result->num_rows > 0) {
   
    // output data of each row
    while($row = $result->fetch_assoc()) {
        echo "<tbody id='myswingTable'><tr><td>" .  $row["ticker"]. "</td><td> " .  $row["emacrossover"]. "</td><td> " .  $row["adxvalue"]. "</td><td> " .  $row["rsivalue"]. "</tbody></td></tr>";
    }
    
} else {
    echo "0 results";
}
 
}


echo '</table>';

$conn->close();
?>
</div>
</body>
</html>